columnSuffix: jbzvxynv
contentColumnType: string
fieldGroup: dc74ce5c-3103-4843-836a-961d909d8643 # Common
handle: buttonStyleSelector
instructions: null
name: 'Button Style Selector'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Transparent
        -
          - value
          - button--transparent
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Primary
        -
          - value
          - button--primary
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
