fieldLayouts:
  5d7b75d4-5aad-41d4-8136-976800678db4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c887ea7e-f4ec-4e38-b7fd-8bef283bebcc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 39d49185-67f9-4d5d-b137-c29a96756245
        userCondition: null
fs: uploads
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
