fieldLayouts:
  b33b4ddf-44e1-496a-9a13-c8d15ad8be88:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b99b4269-dbd2-4b83-8349-ba3d6d28a1ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 50b640eb-fedf-4d1a-86ab-2ac6452a6090 # Entry Selector
            instructions: null
            label: 'Page Selector'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f69a65f7-c03e-40f4-a51c-0905aa5ec7c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 41119b4d-cfd0-4f4f-a946-16749bf6bcf8 # Button Style Selector
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 297a1336-f6a1-426c-b166-c76d5204e8e6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f11f3b4d-f81c-420b-9d6d-0b1f514571f6
        userCondition: null
handle: internal
hasTitleField: true
name: 'Internal Link'
section: 85a35d67-d96b-4841-b4b8-7e364f04e055 # Main Navigation
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
